# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MQTTUIV1MINI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MQTT(object):
    def setupUi(self, MQTT):
        MQTT.setObjectName("MQTT")
        MQTT.resize(529, 679)
        MQTT.setMinimumSize(QtCore.QSize(529, 679))
        MQTT.setMaximumSize(QtCore.QSize(529, 679))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        MQTT.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/face.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MQTT.setWindowIcon(icon)
        MQTT.setIconSize(QtCore.QSize(24, 24))
        MQTT.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MQTT.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MQTT)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 0, 221, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 105, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.BrokerAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.BrokerAddress.setGeometry(QtCore.QRect(170, 50, 181, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.BrokerAddress.setFont(font)
        self.BrokerAddress.setObjectName("BrokerAddress")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 50, 51, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.BrokerPort = QtWidgets.QLineEdit(self.centralwidget)
        self.BrokerPort.setGeometry(QtCore.QRect(420, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.BrokerPort.setFont(font)
        self.BrokerPort.setObjectName("BrokerPort")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 70, 51, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.PassWord = QtWidgets.QLineEdit(self.centralwidget)
        self.PassWord.setGeometry(QtCore.QRect(420, 70, 91, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.PassWord.setFont(font)
        self.PassWord.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.PassWord.setObjectName("PassWord")
        self.UserName = QtWidgets.QLineEdit(self.centralwidget)
        self.UserName.setGeometry(QtCore.QRect(170, 70, 181, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.UserName.setFont(font)
        self.UserName.setObjectName("UserName")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 70, 121, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 90, 121, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.LinkButton = QtWidgets.QPushButton(self.centralwidget)
        self.LinkButton.setGeometry(QtCore.QRect(94, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.LinkButton.setFont(font)
        self.LinkButton.setObjectName("LinkButton")
        self.UnlinkButton = QtWidgets.QPushButton(self.centralwidget)
        self.UnlinkButton.setGeometry(QtCore.QRect(310, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.UnlinkButton.setFont(font)
        self.UnlinkButton.setObjectName("UnlinkButton")
        self.ConnectFlag = QtWidgets.QLabel(self.centralwidget)
        self.ConnectFlag.setGeometry(QtCore.QRect(370, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ConnectFlag.setFont(font)
        self.ConnectFlag.setTabletTracking(False)
        self.ConnectFlag.setAutoFillBackground(False)
        self.ConnectFlag.setAlignment(QtCore.Qt.AlignCenter)
        self.ConnectFlag.setObjectName("ConnectFlag")
        self.ClientID = QtWidgets.QLabel(self.centralwidget)
        self.ClientID.setGeometry(QtCore.QRect(170, 90, 181, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.ClientID.setFont(font)
        self.ClientID.setTabletTracking(False)
        self.ClientID.setAutoFillBackground(False)
        self.ClientID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ClientID.setObjectName("ClientID")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 105, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.Topic = QtWidgets.QLineEdit(self.centralwidget)
        self.Topic.setGeometry(QtCore.QRect(150, 170, 361, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Topic.setFont(font)
        self.Topic.setObjectName("Topic")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 170, 121, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.PublicCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.PublicCheck.setGeometry(QtCore.QRect(50, 260, 101, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.PublicCheck.setFont(font)
        self.PublicCheck.setObjectName("PublicCheck")
        self.FileSelect = QtWidgets.QLineEdit(self.centralwidget)
        self.FileSelect.setGeometry(QtCore.QRect(160, 260, 301, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.FileSelect.setFont(font)
        self.FileSelect.setObjectName("FileSelect")
        self.FileButton = QtWidgets.QPushButton(self.centralwidget)
        self.FileButton.setGeometry(QtCore.QRect(470, 260, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileButton.sizePolicy().hasHeightForWidth())
        self.FileButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FileButton.setFont(font)
        self.FileButton.setObjectName("FileButton")
        self.TimerCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.TimerCheck.setGeometry(QtCore.QRect(50, 280, 101, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.TimerCheck.setFont(font)
        self.TimerCheck.setObjectName("TimerCheck")
        self.SendTimer = QtWidgets.QLineEdit(self.centralwidget)
        self.SendTimer.setGeometry(QtCore.QRect(160, 280, 61, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.SendTimer.setFont(font)
        self.SendTimer.setObjectName("SendTimer")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(220, 280, 21, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(260, 280, 121, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(60, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.SendButton.setFont(font)
        self.SendButton.setObjectName("SendButton")
        self.StopSend = QtWidgets.QPushButton(self.centralwidget)
        self.StopSend.setGeometry(QtCore.QRect(220, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.StopSend.setFont(font)
        self.StopSend.setObjectName("StopSend")
        self.SendClear = QtWidgets.QPushButton(self.centralwidget)
        self.SendClear.setGeometry(QtCore.QRect(380, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.SendClear.setFont(font)
        self.SendClear.setObjectName("SendClear")
        self.Dialog = QtWidgets.QTextEdit(self.centralwidget)
        self.Dialog.setGeometry(QtCore.QRect(50, 190, 461, 71))
        self.Dialog.setObjectName("Dialog")
        self.SaveCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.SaveCheck.setGeometry(QtCore.QRect(50, 450, 101, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.SaveCheck.setFont(font)
        self.SaveCheck.setObjectName("SaveCheck")
        self.RecButton = QtWidgets.QPushButton(self.centralwidget)
        self.RecButton.setGeometry(QtCore.QRect(60, 570, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.RecButton.setFont(font)
        self.RecButton.setObjectName("RecButton")
        self.IntevalTimeout = QtWidgets.QCheckBox(self.centralwidget)
        self.IntevalTimeout.setGeometry(QtCore.QRect(50, 530, 101, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.IntevalTimeout.setFont(font)
        self.IntevalTimeout.setObjectName("IntevalTimeout")
        self.StopRec = QtWidgets.QPushButton(self.centralwidget)
        self.StopRec.setGeometry(QtCore.QRect(220, 570, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.StopRec.setFont(font)
        self.StopRec.setObjectName("StopRec")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 330, 105, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(260, 470, 111, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.Subscribe = QtWidgets.QLineEdit(self.centralwidget)
        self.Subscribe.setGeometry(QtCore.QRect(150, 360, 361, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Subscribe.setFont(font)
        self.Subscribe.setObjectName("Subscribe")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(210, 530, 21, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.BeyondTime = QtWidgets.QLineEdit(self.centralwidget)
        self.BeyondTime.setGeometry(QtCore.QRect(150, 530, 61, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.BeyondTime.setFont(font)
        self.BeyondTime.setObjectName("BeyondTime")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(50, 360, 121, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.RecClear = QtWidgets.QPushButton(self.centralwidget)
        self.RecClear.setGeometry(QtCore.QRect(380, 570, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.RecClear.setFont(font)
        self.RecClear.setObjectName("RecClear")
        self.SaveFile = QtWidgets.QLineEdit(self.centralwidget)
        self.SaveFile.setGeometry(QtCore.QRect(160, 450, 301, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.SaveFile.setFont(font)
        self.SaveFile.setObjectName("SaveFile")
        self.FileButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.FileButton2.setGeometry(QtCore.QRect(470, 450, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileButton2.sizePolicy().hasHeightForWidth())
        self.FileButton2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FileButton2.setFont(font)
        self.FileButton2.setObjectName("FileButton2")
        self.SubTimerCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.SubTimerCheck.setGeometry(QtCore.QRect(50, 470, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.SubTimerCheck.setFont(font)
        self.SubTimerCheck.setObjectName("SubTimerCheck")
        self.MSGCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.MSGCheck.setGeometry(QtCore.QRect(190, 470, 61, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.MSGCheck.setFont(font)
        self.MSGCheck.setObjectName("MSGCheck")
        self.SubCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.SubCheck.setGeometry(QtCore.QRect(120, 470, 61, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.SubCheck.setFont(font)
        self.SubCheck.setObjectName("SubCheck")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(240, 530, 101, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(420, 530, 101, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(50, 550, 131, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(250, 550, 21, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(280, 550, 91, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(490, 550, 21, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(110, 600, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.SelectK1 = QtWidgets.QCheckBox(self.centralwidget)
        self.SelectK1.setGeometry(QtCore.QRect(50, 510, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.SelectK1.setFont(font)
        self.SelectK1.setObjectName("SelectK1")
        self.Key1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Key1.setGeometry(QtCore.QRect(130, 510, 61, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Key1.setFont(font)
        self.Key1.setObjectName("Key1")
        self.Key2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Key2.setGeometry(QtCore.QRect(290, 510, 61, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Key2.setFont(font)
        self.Key2.setText("")
        self.Key2.setObjectName("Key2")
        self.SelectK2 = QtWidgets.QCheckBox(self.centralwidget)
        self.SelectK2.setGeometry(QtCore.QRect(210, 510, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.SelectK2.setFont(font)
        self.SelectK2.setObjectName("SelectK2")
        self.Key3 = QtWidgets.QLineEdit(self.centralwidget)
        self.Key3.setGeometry(QtCore.QRect(450, 510, 61, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Key3.setFont(font)
        self.Key3.setObjectName("Key3")
        self.SelectK3 = QtWidgets.QCheckBox(self.centralwidget)
        self.SelectK3.setGeometry(QtCore.QRect(370, 510, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.SelectK3.setFont(font)
        self.SelectK3.setObjectName("SelectK3")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(330, 610, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.Log = QtWidgets.QLabel(self.centralwidget)
        self.Log.setGeometry(QtCore.QRect(120, 630, 271, 20))
        self.Log.setText("")
        self.Log.setAlignment(QtCore.Qt.AlignCenter)
        self.Log.setObjectName("Log")
        self.SelectK1U = QtWidgets.QCheckBox(self.centralwidget)
        self.SelectK1U.setGeometry(QtCore.QRect(50, 490, 211, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.SelectK1U.setFont(font)
        self.SelectK1U.setObjectName("SelectK1U")
        self.SelectK2U = QtWidgets.QCheckBox(self.centralwidget)
        self.SelectK2U.setGeometry(QtCore.QRect(210, 490, 211, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.SelectK2U.setFont(font)
        self.SelectK2U.setObjectName("SelectK2U")
        self.SelectK3U = QtWidgets.QCheckBox(self.centralwidget)
        self.SelectK3U.setGeometry(QtCore.QRect(370, 490, 159, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.SelectK3U.setFont(font)
        self.SelectK3U.setObjectName("SelectK3U")
        self.TimeOutNUM = QtWidgets.QLabel(self.centralwidget)
        self.TimeOutNUM.setGeometry(QtCore.QRect(330, 530, 91, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.TimeOutNUM.setFont(font)
        self.TimeOutNUM.setTabletTracking(False)
        self.TimeOutNUM.setAutoFillBackground(True)
        self.TimeOutNUM.setText("")
        self.TimeOutNUM.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TimeOutNUM.setObjectName("TimeOutNUM")
        self.Percent = QtWidgets.QLabel(self.centralwidget)
        self.Percent.setGeometry(QtCore.QRect(460, 530, 61, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Percent.setFont(font)
        self.Percent.setTabletTracking(False)
        self.Percent.setAutoFillBackground(True)
        self.Percent.setText("")
        self.Percent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Percent.setObjectName("Percent")
        self.AverageTime = QtWidgets.QLabel(self.centralwidget)
        self.AverageTime.setGeometry(QtCore.QRect(140, 550, 101, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.AverageTime.setFont(font)
        self.AverageTime.setTabletTracking(False)
        self.AverageTime.setAutoFillBackground(True)
        self.AverageTime.setText("")
        self.AverageTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AverageTime.setObjectName("AverageTime")
        self.LongestTime = QtWidgets.QLabel(self.centralwidget)
        self.LongestTime.setGeometry(QtCore.QRect(370, 550, 121, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.LongestTime.setFont(font)
        self.LongestTime.setTabletTracking(False)
        self.LongestTime.setAutoFillBackground(True)
        self.LongestTime.setText("")
        self.LongestTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LongestTime.setObjectName("LongestTime")
        self.ReciveMsg = QtWidgets.QTextEdit(self.centralwidget)
        self.ReciveMsg.setGeometry(QtCore.QRect(50, 380, 461, 71))
        self.ReciveMsg.setObjectName("ReciveMsg")
        self.AlreadyReceived = QtWidgets.QLineEdit(self.centralwidget)
        self.AlreadyReceived.setGeometry(QtCore.QRect(370, 470, 141, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.AlreadyReceived.setFont(font)
        self.AlreadyReceived.setMouseTracking(False)
        self.AlreadyReceived.setFocusPolicy(QtCore.Qt.NoFocus)
        self.AlreadyReceived.setObjectName("AlreadyReceived")
        self.AlreadySend = QtWidgets.QLineEdit(self.centralwidget)
        self.AlreadySend.setGeometry(QtCore.QRect(370, 280, 141, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.AlreadySend.setFont(font)
        self.AlreadySend.setMouseTracking(False)
        self.AlreadySend.setFocusPolicy(QtCore.Qt.NoFocus)
        self.AlreadySend.setObjectName("AlreadySend")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(460, 150, 60, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(461, 340, 60, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        MQTT.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MQTT)
        self.statusbar.setObjectName("statusbar")
        MQTT.setStatusBar(self.statusbar)

        self.retranslateUi(MQTT)
        QtCore.QMetaObject.connectSlotsByName(MQTT)

    def retranslateUi(self, MQTT):
        _translate = QtCore.QCoreApplication.translate
        MQTT.setWindowTitle(_translate("MQTT", "一页MQTT测试"))
        self.label.setText(_translate("MQTT", "一页MQTT测试V1.1"))
        self.label_2.setText(_translate("MQTT", "代理设置："))
        self.label_3.setText(_translate("MQTT", "服务器地址："))
        self.label_4.setText(_translate("MQTT", "端口："))
        self.label_5.setText(_translate("MQTT", "密码："))
        self.label_6.setText(_translate("MQTT", "用  户  名："))
        self.label_7.setText(_translate("MQTT", "客 户 端ID："))
        self.LinkButton.setText(_translate("MQTT", "连接"))
        self.UnlinkButton.setText(_translate("MQTT", "断开连接"))
        self.ConnectFlag.setText(_translate("MQTT", "等待连接"))
        self.ClientID.setText(_translate("MQTT", "等待连接"))
        self.label_8.setText(_translate("MQTT", "发布设置："))
        self.label_9.setText(_translate("MQTT", "发布主题："))
        self.PublicCheck.setText(_translate("MQTT", "发布文件"))
        self.FileButton.setText(_translate("MQTT", "..."))
        self.TimerCheck.setText(_translate("MQTT", "定时发送"))
        self.label_10.setText(_translate("MQTT", "秒"))
        self.label_11.setText(_translate("MQTT", "已发送帧数"))
        self.SendButton.setText(_translate("MQTT", "发送"))
        self.StopSend.setText(_translate("MQTT", "停止发送"))
        self.SendClear.setText(_translate("MQTT", "发送清零"))
        self.SaveCheck.setText(_translate("MQTT", "记录文件"))
        self.RecButton.setText(_translate("MQTT", "订阅"))
        self.IntevalTimeout.setText(_translate("MQTT", "间隔超时"))
        self.StopRec.setText(_translate("MQTT", "停止订阅"))
        self.label_12.setText(_translate("MQTT", "订阅设置："))
        self.label_13.setText(_translate("MQTT", "已接收帧数"))
        self.label_14.setText(_translate("MQTT", "秒"))
        self.label_15.setText(_translate("MQTT", "订阅主题："))
        self.RecClear.setText(_translate("MQTT", "统计清零"))
        self.FileButton2.setText(_translate("MQTT", "..."))
        self.SubTimerCheck.setText(_translate("MQTT", "时间"))
        self.MSGCheck.setText(_translate("MQTT", "原文"))
        self.SubCheck.setText(_translate("MQTT", "主题"))
        self.label_16.setText(_translate("MQTT", "超时帧数"))
        self.label_17.setText(_translate("MQTT", "占比"))
        self.label_18.setText(_translate("MQTT", "平均间隔"))
        self.label_19.setText(_translate("MQTT", "秒"))
        self.label_20.setText(_translate("MQTT", "最长间隔"))
        self.label_21.setText(_translate("MQTT", "秒"))
        self.SaveButton.setText(_translate("MQTT", "保存配置"))
        self.SelectK1.setText(_translate("MQTT", "筛选1"))
        self.SelectK2.setText(_translate("MQTT", "筛选2"))
        self.SelectK3.setText(_translate("MQTT", "筛选3"))
        self.label_22.setText(_translate("MQTT", "联系作者：chlo315@163.com"))
        self.SelectK1U.setText(_translate("MQTT", "筛选1UNIX转秒"))
        self.SelectK2U.setText(_translate("MQTT", "筛选2UNIX转秒"))
        self.SelectK3U.setText(_translate("MQTT", "筛选3UNIX转秒"))
        self.label_23.setText(_translate("MQTT", "QOS:0"))
        self.label_24.setText(_translate("MQTT", "QOS:0"))
